CREATE DATABASE budget_Bunny;
USE budgetBunny;

CREATE TABLE users (
id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
name VARCHAR(255) NOT NULL,
surname VARCHAR(255) NOT NULL,
email VARCHAR(266) NOT NULL,
password VARCHAR(255) NOT NULL);

CREATE TABLE accounts(
id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
debits FLOAT,
deposits FLOAT,
account_name VARCHAR(255) NOT NULL
id_users INT,
FOREIGN KEY (id_users) REFERENCES users(id) ON DELETE CASCADE);

CREATE TABLE transaction (
id INT AUTO_INCREMENT PRIMARY KEY,
description TEXT NOT NULL,
amount FLOAT NOT NULL,
date DATE NOT NULL,
type VARCHAR(255) NOT NULL,
categories VARCHAR(255) NOT NULL,
id_accounts INT,
FOREIGN KEY (id_accounts) REFERENCES accounts(id) ON DELETE CASCADE);

CREATE TABLE transfers(
id INT AUTO_INCREMENT PRIMARY KEY,
from_account INT NOT NULL,
to_account INT NOT NULL,
amount INT NOT NULL,
FOREIGN KEY (from_account) REFERENCES accounts(id) ON DELETE CASCADE,
FOREIGN KEY (to_account) REFERENCES accounts(id) ON DELETE CASCADE);

CREATE TABLE alerts (
id INT AUTO_INCREMENT PRIMARY KEY,
Message TEXT NOT NULL,
is_read BOOLEAN NOT NULL,
id_users INT,
FOREIGN KEY (id_users) REFERENCES users(id) ON DELETE CASCADE);

CREATE TABLE category(
id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
category_name VARCHAR(255) NOT NULL);










